backDjango/gilleshelleu/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from gh import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('projets/', views.liste_projets, name='liste_projets'),
    path('articles/<slug:slug>/', views.post_single, name='list_articles'),
    path('articles/', views.list_articles, name='list_articles'),

    path('experience/', views.experience, name='experience'),
    path('education/', views.education, name='education'),
    path('contact/', views.contact, name='contact'),
    re_path(r'^zenflow/(?P<path>.*)$', serve,
            {'document_root': settings.ZENFLOW_ROOT}),
    path("lorem/", TemplateView.as_view(template_name="lorem.html")),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),


]
if settings.DEBUG:  # seulement en mode développement
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backDjango/gh/models/articles.py
from django.db import models
from ckeditor.fields import RichTextField
from django import forms
from .langage import Langage
from django.template.defaultfilters import slugify
from django.utils.crypto import get_random_string


class Article(models.Model):
    titre = models.CharField(max_length=255)
    description_courte = models.CharField(
        max_length=350)
    image = models.ImageField(upload_to='articles/', blank=True, null=True,)
    VISIBILITY_TYPE = [("draft", "Draft"), ("public",
                                            "Public"), ("private", "Private")]
    date = models.DateField(blank=True, null=True, max_length=255)
    visibility = models.CharField(
        max_length=30, choices=VISIBILITY_TYPE, default="draft")
    description = RichTextField(blank=True, null=True)
    langage = models.ManyToManyField(
        Langage, verbose_name="Langages", blank=True)
    # liens = models.JSONField(blank=True, null=True)
    slug = models.SlugField(max_length=255, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.titre or Article.objects.filter(titre=self.titre).exclude(pk=self.pk).exists():
            # Si le titre est vide ou en double, générer un slug aléatoire
            self.slug = get_random_string(8)
        else:
            self.slug = slugify(self.titre)

        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return self.titre

backDjango/gh/models/certificat.py
from django.db import models
from ckeditor.fields import RichTextField
from django import forms


class Certificat(models.Model):
    titre = models.CharField(max_length=255)
    formateur = models.CharField(blank=True, null=True, max_length=255)
    annee = models.CharField(blank=True, null=True, max_length=255)
    display_order = models.IntegerField(default=0)

    def __str__(self):
        return self.titre

backDjango/gh/models/contact.py
from django.db import models
from ckeditor.fields import RichTextField
from django import forms
from friendly_captcha.fields import FrcCaptchaField


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']
    captcha = FrcCaptchaField()

backDjango/gh/models/langage.py
from django.db import models
from django import forms


class Langage(models.Model):
    nom = models.CharField(max_length=50, unique=True, blank=True, null=True,)

    def __str__(self):
        return self.nom

backDjango/gh/models/liens.py
from django.db import models
from ckeditor.fields import RichTextField
from django import forms
from friendly_captcha.fields import FrcCaptchaField
from .projet import Projet


# des liens pour les projets


class Lien(models.Model):
    projet = models.ForeignKey(
        Projet, on_delete=models.CASCADE, related_name="liens")
    intitule = models.CharField(max_length=255)
    url = models.URLField()

    def __str__(self):
        return self.intitule

# images pour faire un carousel


class ImageProjet(models.Model):
    projet = models.ForeignKey(
        Projet, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to='projets/images/')

    def __str__(self):
        return f"Image for {self.projet.titre}"

backDjango/gh/models/projet.py
from django.db import models
from ckeditor.fields import RichTextField
from django import forms
from friendly_captcha.fields import FrcCaptchaField
from .langage import Langage


class Projet(models.Model):
    titre = models.CharField(max_length=255)
    soustitre = models.CharField(blank=True, null=True, max_length=255)
    image = models.ImageField(upload_to='projets/')
    annee = models.CharField(blank=True, null=True, max_length=255)
    display_order = models.IntegerField(default=0)

    description = RichTextField(blank=True, null=True)

    langages = models.ManyToManyField(Langage)
    top = models.BooleanField(default=False)

    # liens = models.JSONField(blank=True, null=True)

    def __str__(self):
        return self.titre

backDjango/gh/views.py
from django.shortcuts import render, get_object_or_404
from django.utils.html import mark_safe, escape
from .models import Langage, Projet, ContactForm, Certificat, Article
from django.core.serializers import serialize
from django.core.mail import send_mail
from django.conf import settings
from decouple import config, Csv


def home(request):
    # Récupère tous les projets pour les afficher dans la page d'accueil.
    projets = Projet.objects.all()
    langage_filter = request.GET.get('langage')
    if langage_filter:
        projets = Projet.objects.filter(langages__nom=langage_filter)
    else:
        projets = Projet.objects.all().order_by('display_order')

    for projet in projets:
        liens = serialize('json', projet.liens.all())
        projet.liens_json = liens
        projet.description = mark_safe(projet.description)
        langages = Langage.objects.all()
        articles = Article.objects.all().order_by("-date").filter(visibility="public")

    return render(request, 'home.html', {'projets': projets, 'langages': langages, "articles": articles})


def liste_projets(request):
    langage_filter = request.GET.get('langage')
    if langage_filter:
        projets = Projet.objects.filter(langages__nom=langage_filter)
    else:
        projets = Projet.objects.all().order_by('display_order')
    for projet in projets:
        liens = serialize('json', projet.liens.all())
        projet.liens_json = liens
        projet.description = mark_safe(projet.description)
    # pour boucler avec le filtre
    langages = Langage.objects.all()

    return render(request, 'liste_projets.html', {'projets': projets, 'langages': langages})


def list_articles(request):
    articles = Article.objects.all().order_by("-date").filter(visibility="public")
    return render(request, "blog.html", {"articles": articles})


def post_single(request, slug):
    article = get_object_or_404(Article, slug=slug)
    prev_article = Article.objects.filter(
        date__lt=article.date).order_by('-date').first()
    next_article = Article.objects.filter(
        date__gt=article.date).order_by('date').first()
    return render(request, 'post_single.html', {
        'article': article,
        'prev_article': prev_article,
        'next_article': next_article
    })


def experience(request):
    return render(request, 'experience.html')


def education(request):
    certificats = Certificat.objects.all().order_by("display_order")

    return render(request, 'education.html', {"certificats": certificats})

# Formulaire de contact


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save()
            subject = f"Message de {form.cleaned_data['name']}"
            message = form.cleaned_data['message']
            from_email = form.cleaned_data['email']

            # Envoyer un email
            send_mail(
                subject,
                message,
                from_email,
                [config('EMAIL_HOST_USER')],
                fail_silently=False,
            )
            return render(request, 'contact_success.html')
    else:
        form = ContactForm()

    return render(request, 'contact.html', {'form': form})

backDjango/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="fr">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Gilles Helleu</title>
		<link rel="stylesheet" href="{% static 'css/style.css' %}" />
		<link rel="stylesheet" href="{% static 'css/menu.css' %}" />
		<link rel="stylesheet" href="{% static 'css/style_responsive.css' %}" />

		<script
			src="https://code.jquery.com/jquery-3.7.1.min.js"
			integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
			crossorigin="anonymous"></script>
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
		<script src="{% static 'js/bootstrap.bundle.min.js' %} " defer></script>
		<script src="{% static 'js/popup.js' %}" defer></script>
	</head>

	<link
		rel="icon"
		type="image/png"
		href=" {% static 'images/favicon.png' %} " />

	<header class="page-header">
		<div class="logo">
			<a href="/"
				><img
					src="{% static 'images/logoGHblc.png' %}"
					alt="Logo Gilles Helleu"
			/></a>
		</div>
		<div class="header-contact">{% include "contact_boutons.html" %}</div>
		<div id="burger-menu">
			<span></span>
		</div>
		<div id="menu">
			<ul>
				<li><a href="/projets/">Projets</a></li>
				<li><a href="/experience/">Expérience</a></li>
				<li><a href="/education/">Formations</a></li>
				<li><a href="/articles/">mémos</a></li>
				<li><a href="/contact/">Contact</a></li>
			</ul>
			<div class="buttonsmenu">{% include "contact_boutons.html" %}</div>
		</div>
	</header>
	<body>
		<main id="main">{% block content %}{% endblock %}</main>
		<script>
			window.onscroll = function () {
				makeSticky();
			};

			var header = document.querySelector("header");
			var sticky = header.offsetTop;

			function makeSticky() {
				if (window.pageYOffset > sticky) {
					header.classList.add("sticky");
				} else {
					header.classList.remove("sticky");
				}
			}
		</script>
		<script src="{% static 'js/burger.js' %}"></script>
		<script>
			document
				.getElementById("techSelect")
				.addEventListener("change", function () {
					let selectedValue = this.value;

					// Si "Technologies" est sélectionné, affichez tous les projets
					if (selectedValue === "./") {
						displayProjectsByLangage(null);
					} else {
						let langageToFilter = new URLSearchParams(selectedValue).get(
							"langage"
						);
						displayProjectsByLangage(langageToFilter);
					}
				});

			function displayProjectsByLangage(langage) {
				let projects = document.querySelectorAll(".projectbloc");

				projects.forEach((project) => {
					let projectLangages = project.dataset.langages.split(",");
					if (langage === null || projectLangages.includes(langage)) {
						project.style.display = "block";
					} else {
						project.style.display = "none";
					}
				});
			}

			document.addEventListener("DOMContentLoaded", function () {
				// Gestionnaire pour les cartes cliquables
				let projectBlocks = document.querySelectorAll(".projectbloc");
				projectBlocks.forEach((block) => {
					block.addEventListener("click", function (event) {
						// Empêche la propagation si un lien ou un bouton est cliqué
						if (
							event.target.tagName === "A" ||
							event.target.tagName === "BUTTON"
						) {
							return;
						}

						// Récupération des données du projet
						let projectTitle = this.getAttribute("data-project-title");
						let projectDescription = this.getAttribute(
							"data-project-description"
						);
						let projectUrls =
							this.getAttribute("data-project-urls").split("|||");
						let projectIntitules = this.getAttribute(
							"data-project-intitules"
						).split("|||");
						let projectLangages = this.getAttribute(
							"data-project-langages"
						).split(",");
						let projectImages = this.getAttribute("data-project-images").split(
							","
						);
						let projectAnnee = this.getAttribute("data-project-annee");

						// Configuration de la modal avec les données du projet
						let modal = $("#projectDetailModal");
						modal.find(".modal-title").text(projectTitle);
						modal.find(".annee").text(projectAnnee);
						modal.find(".projetdescription").html(projectDescription);
						// ... (autres configurations de la modal)

						// Affichage de la modal
						modal.modal("show");
					});
				});

				// Initialisation de la modal pour la première ouverture
				$("#projectDetailModal").on("show.bs.modal", function (event) {
					let button = $(event.relatedTarget);
					let projectTitle = button.data("project-title");
					let projectDescription = button.data("project-description");
					let projectUrls = button.data("project-urls").split("|||");
					let projectIntitules = button.data("project-intitules").split("|||");
					let projectLangages = button.data("project-langages").split(",");
					let projectImages = button.data("project-images").split(",");
					let projectAnnee = button.data("project-annee");

					let modal = $(this);
					modal.find(".modal-title").text(projectTitle);
					modal.find(".annee").text(projectAnnee);
					modal.find(".projetdescription").html(projectDescription);
					let langagesHtml = projectLangages
						.map(function (langage) {
							return `<span class="badge bg-dark">${langage}</span>`;
						})
						.join(" ");

					modal.find(".project-langages").html(langagesHtml);

					let liensHtml = projectUrls
						.map(function (url, index) {
							let intitule = projectIntitules[index];
							if (url) {
								return `<a href="${url}" target="_blank" class="buttonp my-5">${intitule}</a>`;
							}
						})
						.join("");

					modal.find(".projets-liens").html(liensHtml);

					// Mettez à jour les images du carrousel
					let carouselElement = modal.find(".carousel");
					let carouselInner = modal.find(".carousel-inner");

					// Mettez à jour les images du carrousel
					if (projectImages.length > 0 && projectImages[0] !== "") {
						let carouselContent = projectImages
							.map(
								(img, index) => `
                <div class="carousel-item ${index === 0 ? "active" : ""}">
                    <img src="${img}" class="d-block imgcarousel" alt="...">
                </div>
            `
							)
							.join("");
						carouselInner.html(carouselContent);
						carouselElement.show();
					} else {
						carouselElement.hide();
					}
				});
			});
		</script>

		<footer>© Gilles Helleu</footer>
	</body>
</html>

backDjango/templates/bloc_articles.html
<div class="article-container">
	{% for article in articles %}
	<a href="/articles/{{ article.slug }}"
		><div class="article-card">
			<div class="article-content">
				<h2 class="article-title">{{ article.titre }}</h2>
				<div class="tagsarticles">
					{% for l in article.langage.all %}
					<span class="langages badge bg-article">{{ l }}</span>
					{% endfor %}
				</div>

				<p class="article-description">{{ article.description_courte }}</p>
				<p class="read-more">Lire la suite...</p>
			</div>
		</div></a
	>

	{% endfor %}
</div>

backDjango/templates/bloc_projets.html
<div class="filtres">
	<select id="techSelect">
		<option value="./">Toutes les technologies</option>
		{% for langage in langages %}
		<option value="?langage={{ langage }}">{{ langage }}</option>
		{% endfor %}
	</select>
	<button id="resetButton" onclick="window.location.href='./'">
		Réinitialiser
	</button>
</div>

<div class="row">
	{% for projet in projets %} {% if projet.top %}

	<div
		class="projectbloc clickable col-11 col-md-3 m-3 p-2"
		data-langages="{% for langage in projet.langages.all %}{{ langage.nom }}{% if not forloop.last %},{% endif %}{% endfor %}"
		data-bs-toggle="modal"
		data-bs-target="#projectDetailModal"
		data-project-id="{{ projet.id }}"
		data-project-title="{{ projet.titre }}"
		data-project-description="{{ projet.description }}"
		data-project-annee="{{ projet.annee }}"
		data-project-urls="{% for lien in projet.liens.all %}{{ lien.url|safe }}{% if not forloop.last %}|||{% endif %}{% endfor %}"
		data-project-intitules="{% for lien in projet.liens.all %}{{ lien.intitule|safe }}{% if not forloop.last %}|||{% endif %}{% endfor %}"
		data-project-images="{% for img in projet.images.all %}{{ img.image.url }}{% if not forloop.last %},{% endif %}{% endfor %}"
		data-project-liens="{% for lien in projet.liens.all %}{{ lien.url }}{% if not forloop.last %},{% endif %}{% endfor %}"
		data-project-langages="{% for langage in projet.langages.all %}{{ langage }}{% if not forloop.last %},{% endif %}{% endfor %}">
		<!-- img<
				src="{{ projet.image.url }}"
				alt="{{ projet.titre }}"
				class="img-fluid" /> -->
		<h2 class="titreprojet">{{ projet.titre }}</h2>
		<div class="">
			{% for langage in projet.langages.all %}
			<span class="langages badge bg-light">{{ langage }}</span>

			{% endfor %}
		</div>
		<span class="projetdescription">{{ projet.annee }}</span>

		<div class="projetdescription">{{ projet.soustitre }}</div>
		<span class="buttonp">En savoir +</span>
		<!-- <div class="liens-projet">
      {% for lien in projet.liens.all %}

      <a href="{{ lien.url }}" target="_blank" class="buttonp"
        >{{ lien.intitule }}
      </a>
    

      {% endfor %}
    </div> -->
	</div>
	{% endif %} {% endfor %}
</div>

<!-- Espace entre les deux sections -->
<div style="margin-top: 20px"></div>

<!-- Projets avec top=False -->
<div class="row">
	{% for projet in projets %} {% if not projet.top %}
	<div
		class="projectbloc clickable col-11 col-md-3 m-3 p-2"
		data-langages="{% for langage in projet.langages.all %}{{ langage.nom }}{% if not forloop.last %},{% endif %}{% endfor %}"
		data-bs-toggle="modal"
		data-bs-target="#projectDetailModal"
		data-project-id="{{ projet.id }}"
		data-project-title="{{ projet.titre }}"
		data-project-description="{{ projet.description }}"
		data-project-annee="{{ projet.annee }}"
		data-project-urls="{% for lien in projet.liens.all %}{{ lien.url|safe }}{% if not forloop.last %}|||{% endif %}{% endfor %}"
		data-project-intitules="{% for lien in projet.liens.all %}{{ lien.intitule|safe }}{% if not forloop.last %}|||{% endif %}{% endfor %}"
		data-project-images="{% for img in projet.images.all %}{{ img.image.url }}{% if not forloop.last %},{% endif %}{% endfor %}"
		data-project-liens="{% for lien in projet.liens.all %}{{ lien.url }}{% if not forloop.last %},{% endif %}{% endfor %}"
		data-project-langages="{% for langage in projet.langages.all %}{{ langage }}{% if not forloop.last %},{% endif %}{% endfor %}">
		<!-- img<
				src="{{ projet.image.url }}"
				alt="{{ projet.titre }}"
				class="img-fluid" /> -->
		<h2 class="titreprojet-small">{{ projet.titre }}</h2>
		<div class="">
			{% for langage in projet.langages.all %}
			<span class="langages badge-small bg-light">{{ langage }}</span>

			{% endfor %}
		</div>

		<span class="buttonp">En savoir +</span>
		<!-- <div class="liens-projet">
      {% for lien in projet.liens.all %}

      <a href="{{ lien.url }}" target="_blank" class="buttonp"
        >{{ lien.intitule }}
      </a>
    

      {% endfor %}
    </div> -->
	</div>
	{% endif %} {% endfor %}
</div>

<!-- MODALE POUR CHAQUE PROJET -->

<div
	class="modal fade"
	id="projectDetailModal"
	tabindex="-1"
	aria-labelledby="projectDetailModalLabel"
	aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="projectDetailModalLabel">
					{{ projet.titre }}
				</h5>
				<button
					type="button"
					class="btn-close"
					data-bs-dismiss="modal"
					aria-label="Fermer"></button>
			</div>
			<div class="modal-body">
				<h2 class="titreprojet"></h2>
				<div class="liens-projet">
					{% for lien in projet.liens.all %}

					<a href="{{ lien.url }}" target="_blank" class="buttonp"
						>{{ lien.intitule }}
					</a>

					{% endfor %}
				</div>
				<div class="projetdescription">{{ projet.description }}</div>
				<div class="row">
					<div id="carousel-{{ projet.id }}" class="carousel col-md-5 mx-md-3">
						<div class="carousel-inner">
							{% for img in projet.images.all %}
							<div
								class="carousel-item {% if forloop.first %}active{% endif %}">
								<div class="container">
									<div class="row">
										<div class="col-md-4">
											<img
												src="{{ img.image.url }}"
												class="d-block w-100"
												alt="{{ projet.titre }}" />
										</div>
									</div>
								</div>
							</div>
							{% endfor %}
						</div>
						<button
							class="carousel-control-prev"
							type="button"
							data-bs-target="#carousel-{{ projet.id }}"
							data-bs-slide="prev">
							<span
								class="carousel-control-prev-icon"
								aria-hidden="true"></span>
							<span class="visually-hidden">Précédent</span>
						</button>
						<button
							class="carousel-control-next"
							type="button"
							data-bs-target="#carousel-{{ projet.id }}"
							data-bs-slide="next">
							<span
								class="carousel-control-next-icon"
								aria-hidden="true"></span>
							<span class="visually-hidden">Suivant</span>
						</button>
					</div>
					<div class="col-md-5 mx-3 py-5">
						<div class="project-langages"></div>
						<div class="annee"></div>
						<div class="projets-liens"></div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
					Fermer
				</button>
			</div>
		</div>
	</div>
</div>

backDjango/templates/blog.html
{% extends "base.html" %} {% block content %} {% include "bloc_articles.html" %}
{% endblock %}

backDjango/templates/contact.html
{% extends "base.html" %} {% block content %}

<form method="post">
	{% csrf_token %}
	<label for="id_name">Votre nom:</label>
	{{ form.name }}
	<label for="id_email">Votre email:</label>
	{{ form.email }}
	<label for="id_message">Votre message:</label>
	{{ form.message }}

	<input type="submit" value="Envoyer" />
</form>

{% endblock %}

backDjango/templates/contact_boutons.html
<div class="contact-tag-div flex flex-wrap gap-2">
	<div class="contact-tag btn px-3 my-2 me-3">
		<a
			href="https://github.com/gillesah"
			target="_blank"
			rel="noopener noreferrer"
			><svg
				stroke="currentColor"
				fill="currentColor"
				stroke-width="0"
				role="img"
				viewBox="0 0 24 24"
				class="mr-2"
				height="16"
				width="16"
				xmlns="http://www.w3.org/2000/svg">
				<title></title>

				<path
					d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"></path>
			</svg>
			Github
		</a>
	</div>
	<div class="contact-tag btn px-3 my-2 me-3">
		<a
			href="https://www.linkedin.com/in/gilleshelleu/"
			target="_blank"
			rel="noopener noreferrer"
			><svg
				stroke="currentColor"
				fill="currentColor"
				stroke-width="0"
				role="img"
				viewBox="0 0 24 24"
				class="mr-2"
				height="16"
				width="16"
				xmlns="http://www.w3.org/2000/svg">
				<title></title>
				<path
					d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"></path>
			</svg>
			Linkedin
		</a>
	</div>
	<div class="contact-tag btn px-3 my-2 me-3">
		<a
			href="mailto:helleugilles@gmail.com"
			target="_blank"
			rel="noopener noreferrer"
			><svg
				stroke="currentColor"
				fill="currentColor"
				stroke-width="0"
				viewBox="0 0 20 20"
				aria-hidden="true"
				class="mr-2"
				height="16"
				width="16"
				xmlns="http://www.w3.org/2000/svg">
				<path
					d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z"></path>
				<path
					d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z"></path>
			</svg>
			Email
		</a>
	</div>
	<div class="contact-tag btn px-3 my-2 me-3">
		<a
			href="./static/images/GillesHelleu_CV.pdf"
			target="_blank"
			rel="noopener noreferrer"
			><svg
				stroke="currentColor"
				fill="currentColor"
				xmlns="http://www.w3.org/2000/svg"
				height="16"
				viewBox="0 -960 960 960"
				width="16">
				<path
					d="M480-240 240-480l56-56 144 144v-368h80v368l144-144 56 56-240 240Z" />
			</svg>
			CV
		</a>
	</div>
</div>

backDjango/templates/contact_success.html
{% extends "base.html" %} {% block content %}
<p>Merci pour votre message!</p>

{% endblock %}

backDjango/templates/liste_projets.html
{% extends "base.html" %} {% block content %} {% include "bloc_projets.html" %}
{% endblock %}

backDjango/templates/post_single.html
{% extends "base.html" %} {% block content %}
<div class="breadcrumb">
	<a href="{% url 'home' %}">Accueil </a> &gt;
	<a href="{% url 'list_articles' %}"> Articles </a> &gt;
	<span> {{ article.titre }}</span>
</div>
<div class="single-post-container">
	<div class="post-content">
		<h1 class="post-title">{{ article.titre }}</h1>
		<p class="post-date">
			Le {{ article.date|date:"d F Y" }} | {% for l in article.langage.all %}
			<span class="langages badge bg-article">{{ l }}</span>
			{% endfor %}
		</p>
		<div class="post-description">{{ article.description|safe }}</div>
		<div class="article-navigation">
			{% if prev_article %}
			<div class="nav-card">
				<a href="/articles/{{ prev_article.slug }}">
					<span class="nav-arrow">&larr;</span>
					<span class="nav-title">{{ prev_article.titre }}</span>
				</a>
			</div>
			{% endif %} {% if next_article %}
			<div class="nav-card">
				<a href="/articles/{{ next_article.slug }}">
					<span class="nav-title">{{ next_article.titre }}</span>
					<span class="nav-arrow">&rarr;</span>
				</a>
			</div>
			{% endif %}
		</div>
	</div>
</div>

{% endblock %}